version: 2

defaults: &defaults
  working_directory: ~/ezyconfig
  docker:
    - image: cimg/node:16.16.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Tests
          command: npm test

      - run:
          name: Build
          command: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/ezyconfig
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ezyconfig

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/ezyconfig/.npmrc

      - run:
          name: Publish
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/

      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
